---

- name: Create temporary directory
  tempfile:
    state: directory
    suffix: _example
  register: temp_dir
  notify:
    - Delete temporary directory

- name: Render sample AM keystore password
  copy:
    content: "{{ sample_am_keystore_pass }}"
    dest: "{{ temp_dir.path }}/keystore_pwd"
    owner: root
    group: root
    mode:  0600

- name: Create encrypted sample AM keystore private key password
  shell:
    cmd: "{{ ampassword }} -e {{ temp_dir.path }}/keystore_pwd > {{ sample_am_keypass_path }}"

- name: Create encrypted sample AM keystore password
  shell:
    cmd: "{{ ampassword }} -e {{ temp_dir.path }}/keystore_pwd > {{ sample_am_storepass_path }}"

- name: Protect encrypted passwords
  file:
    path: "{{ item }}"
    owner: jboss
    group: jboss
    mode:  0400
  loop:
    - "{{ sample_am_keypass_path }}"
    - "{{ sample_am_storepass_path }}"

- name: Create new PKCS12 keystore from JKS keystore
  command: >
    keytool
      -importkeystore
      -srckeystore  {{ acs_am_keystore_path }}
      -srcstorepass {{ acs_am_keystore_pass }}
      -srcstoretype jks
      -destkeystore  {{ sample_am_keystore_path }}
      -deststorepass {{ sample_am_keystore_pass }}
      -destkeypass   {{ sample_am_keystore_pass }}
      -deststoretype pkcs12
      -noprompt
  register: cmd_result
  no_log: true

- name: Show result of keystore creation
  debug:
    msg:
      - "{{ cmd_result.stdout }}"
      - "{{ cmd_result.stderr }}"

- name: Ensure new PKCS12 keystore has restricted file permissions
  file:
    path: "{{ sample_am_keystore_path }}"
    owner: root
    group: root
    mode:  0644

- name: Import SAML certs from AM default JKS keystore
  command: >
    keytool
      -importkeystore
      -srckeystore       {{ am_default_keystore_dir }}/keystore.jks
      -srcstorepass:file {{ am_default_keystore_dir }}/.storepass
      -srckeypass:file   {{ am_default_keystore_dir }}/.keypass
      -srcstoretype jks
      -srcalias {{ item }}
      -destkeystore       {{ sample_am_keystore_path }}
      -deststorepass:file {{ temp_dir.path }}/keystore_pwd
      -destkeypass:file   {{ temp_dir.path }}/keystore_pwd
      -deststoretype pkcs12
      -noprompt
  loop:
    - test
    - rsajwtsigningkey

- name: Import SAML certs from AM default JCEKS keystore
  command: >
    keytool
      -importkeystore
      -srckeystore       {{ am_default_keystore_dir }}/keystore.jceks
      -srcstorepass:file {{ am_default_keystore_dir }}/.storepass
      -srckeypass:file   {{ am_default_keystore_dir }}/.keypass
      -srcstoretype jceks
      -srcalias {{ item }}
      -destkeystore       {{ sample_am_keystore_path }}
      -deststorepass:file {{ temp_dir.path }}/keystore_pwd
      -destkeypass:file   {{ temp_dir.path }}/keystore_pwd
      -deststoretype pkcs12
      -noprompt
  loop:
    - selfserviceenctest
    - es256test
    - es384test
    - es512test
