---
- name: Get the current caller identity information
  amazon.aws.aws_caller_info:
  register: caller_info

- name: Delete existing resources
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command: >
    ccoctl aws delete --name {{ caller_info.account }}-dep{{ deployment_number }} --region=us-gov-west-1
- name: Remove ccoctl directory
  ansible.builtin.file:
    path: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/ccoctl"
    state: absent

- name: Create ccoctl directory
  ansible.builtin.file:
    path: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/ccoctl"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Generate credential requests
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command: >
    /home/{{ ansible_user }}/.local/bin/oc adm release extract --credentials-requests --cloud=aws  \
    --from=quay.io/openshift-release-dev/ocp-release:{{ openshift_major_version
    }}.{{ openshift_minor_version }}.{{ openshift_patch_version }}-x86_64 --to={{ config_dir }}/deployment{{ deployment_number }}/ocp/ccoctl/credrequests
  become: true

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/ccoctl/credrequests"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
  become: true

- name: Add credential request for EFS
  ansible.builtin.template:
    src: "openshift-cluster-csi-drivers-aws-efs-cloud-credentials-credentials.yaml.j2"
    dest: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/ccoctl/credrequests/openshift-cluster-csi-drivers-aws-efs-cloud-credentials-credentials.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Generate all
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command: >
    ccoctl aws create-all --name={{ caller_info.account }}-dep{{ deployment_number }} \
    --region=us-gov-west-1 --credentials-requests-dir={{ config_dir }}/deployment{{
    deployment_number }}/ocp/ccoctl/credrequests --output-dir={{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster
  args:
    chdir: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster/"

- name: Copy tls
  ansible.builtin.copy:
    src: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster/tls/"
    dest: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: preserve
