---

- name: Ensure firewalld is installed
  package:
    name: firewalld
    state: present

- name: Enable and start firewalld
  service:
    name: firewalld
    state: started
    enabled: true

# We should eventually use https

- name: Allow http protocol
  firewalld:
    service: http
    immediate: true
    permanent: true
    state: enabled

