---
- name: Install httpd
  ansible.builtin.package:
    name: httpd
    state: present

- name: Enable and start httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
