---

- name: Copy managed CA certificate bundle to sample trust anchors directory
  copy:
    src:  "{{ pki_subdir }}/trust/ca-bundle.pem"
    dest: "{{ pki_dir }}/sample/trust/anchors/"
    owner: root
    group: root
    mode:  0644

- name: Assemble sample CA certificate bundle
  assemble:
    src:  "{{ pki_dir }}/sample/trust/anchors"
    dest: "{{ pki_dir }}/sample/trust/sample-ca-bundle.pem"
    owner: root
    group: root
    mode:  0644

