---

- name: Create sample PKI sub-directories
  file:
    path: "{{ pki_dir }}/sample/{{ item }}"
    state: directory
    owner: root
    group: root
    mode:  0755
  loop:
    - "ca"
    - "ca/root"
    - "trust"
    - "trust/anchors"
    - "workspace"

