---

# This generates a self-signed DIL certificate

- name: Generate private key
  openssl_privatekey:
    path: "{{ pki_dir }}/sample/workspace/dil-ca.key"
    type: RSA
    size: 2048
    owner: root
    group: root
    mode:  0600

- name: Generate certificate signing request (CSR)
  openssl_csr:
    path:            "{{ pki_dir }}/sample/workspace/dil-ca.csr"
    privatekey_path: "{{ pki_dir }}/sample/workspace/dil-ca.key"
    basic_constraints:
      - "CA:TRUE"
    basic_constraints_critical: true
    country_name: US
    state_or_province_name: Virginia
    locality_name: Arlington
    organization_name: Solers,Inc.
    common_name: appsample-dil-services-ca

- name: Generate certificate
  openssl_certificate:
    path:            "{{ pki_dir }}/sample/workspace/dil-ca.crt"
    csr_path:        "{{ pki_dir }}/sample/workspace/dil-ca.csr"
    privatekey_path: "{{ pki_dir }}/sample/workspace/dil-ca.key"
    provider: selfsigned

- name: Copy certificate to required locations
  copy:
    src:  "{{ pki_dir }}/sample/workspace/dil-ca.crt"
    dest: "{{ item }}"
    owner: root
    group: root
    mode:  0644
  loop:
    - "{{ pki_dir }}/sample/ca/root"
    - "{{ pki_dir }}/sample/trust/anchors"

