---
- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Configure firewall to allow api port
  ansible.posix.firewalld:
    port: "{{ api_port }}/tcp"
    immediate: true
    permanent: true
    state: enabled

- name: Configure firewall to allow machine config port
  ansible.posix.firewalld:
    port: "{{ machine_config_port }}/tcp"
    immediate: true
    permanent: true
    state: enabled
