---
- name: Import task.
  ansible.builtin.import_tasks: firewall.yml
- name: Import task.
  ansible.builtin.import_tasks: selinux.yml
- name: Import task.
  ansible.builtin.import_tasks: haproxy.yml
