---

application_name: application_example

application_fqdn: "{{ application_name }}.{{ apps_base_domain }}"

application_site_name: "USS_EAGLE"

application_storage_size: "10Gi"

application_storage_class: "file"
