---

- name: Create artifactory database deployment config
  k8s:
    definition: "{{ lookup('template', artifactorydb_deploymentconfig_manifest) }}"

- name: Ensure artifactory database pod is running (2m)
  k8s_info:
    kind: Pod
    namespace: application-sample
    field_selectors:
      - status.phase=Running
    label_selectors:
      - app=artifactorydb
  register: pod_result
  until: pod_result.resources | count > 0
  delay: 10
  retries: 12

- name: Create artifactory deployment config
  k8s:
    definition: "{{ lookup('template', artifactory_deploymentconfig_manifest) }}"
