---

- name: Create marketplace database deployment config
  k8s:
    definition: "{{ lookup('template', marketplacedb_deploymentconfig_manifest) }}"

- name: Ensure marketplace database pod is running (2m)
  k8s_info:
    kind: Pod
    namespace: application-sample
    field_selectors:
      - status.phase=Running
    label_selectors:
      - app=marketplacedb
  register: pod_result
  until: pod_result.resources | count > 0
  delay: 10
  retries: 12

- name: Create marketplace deployment config
  k8s:
    definition: "{{ lookup('template', marketplace_deploymentconfig_manifest) }}"

