---

- name: Configure image registy to use PVC for storage and use default route
  k8s:
    definition:
      apiVersion: imageregistry.operator.openshift.io/v1
      kind: Config
      metadata:
        name: cluster
      spec:
        managementState: Managed
        defaultRoute: true
    state: present