---

- name: Give sample user image registry viewer role binding
  command:
    cmd: "oc policy add-role-to-user registry-viewer sample"

- name: Give sample user image registry editor role binding
  command:
    cmd: "oc policy add-role-to-user registry-editor sample"