---
- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Configure firewall to allow http
  ansible.posix.firewalld:
    port: "{{ http_port }}/tcp"
    immediate: true
    permanent: true
    state: enabled

- name: Configure firewall to allow https
  ansible.posix.firewalld:
    port: "{{ https_port }}/tcp"
    immediate: true
    permanent: true
    state: enabled
