---

application_name: application_example

application_owf_admin_group: ADMIN

application_owf_extern_admin_group: EXTERN_ADMIN

application_dir: /opt/sample

keystore_dir: /etc/pki/java

ssoadm_dir: /opt/ssoadm
