---
- name: Create ocp4 dir
  ansible.builtin.file:
    path: "{{ config_dir }}/deployment{{ deployment_number }}/ocp"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Check if metadata file exists.
  ansible.builtin.stat:
    path: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster/metadata.json"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: metadata_exists

- name: Get the current caller identity information
  amazon.aws.aws_caller_info:
  register: caller_info

- name: Create cluster directory
  ansible.builtin.file:
    path: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  when: not metadata_exists.stat.exists

- name: Get Metadata file from S3
  amazon.aws.s3_object:
    bucket: "sample-{{ caller_info.account }}-openshift"
    object: "/deployment{{ deployment_number }}/cluster/metadata.json"
    dest: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster/metadata.json"
    mode: get
  when: not metadata_exists.stat.exists

- name: Disable termination protection on OpenShift nodes
  amazon.aws.ec2_instance:
    filters:
      tag:sampleDeploymentNumber: "{{ deployment_number }}"
      platform-details: "Linux/UNIX"
      instance-state-name: running
    termination_protection: false

- name: Destroys existing cluster if exists
  changed_when: destroy_results.rc != 0
  ansible.builtin.command: >
    openshift-install destroy cluster --dir={{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster/ --log-level=debug
  ignore_errors: true
  timeout: 300
  register: destroy_results

- name: Remove cluster directory
  ansible.builtin.file:
    path: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster"
    state: absent

- name: Create cluster directory
  ansible.builtin.file:
    path: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Set install config source.
  ansible.builtin.set_fact:
    source: "install-config.yaml.j2"
  when: ocp_platform == "none"

- name: Set install config source.
  ansible.builtin.set_fact:
    source: "aws-install-config.yaml.j2"
  when: ocp_platform == "aws"

- name: Get deployment ssh key id
  changed_when: keyId.rc != 0
  ansible.builtin.command: >
    aws ssm get-parameter --name /sample/ec2/sample-deployment-{{ deployment_number }}/ec2/default-key/id \
    --query Parameter.Value --with-decryption --output=text
  register: keyId

- name: Get deployment ssh key id
  changed_when: ssh_key.rc != 0
  ansible.builtin.command: >
    aws ssm get-parameter --name /ec2/keypair/{{ keyId.stdout }}/public --query Parameter.Value --with-decryption --output=text
  register: ssh_key

- name: Get deployment ssh key contents
  changed_when: sshKey.rc != 0
  ansible.builtin.command: >
    aws ssm get-parameter --name /ec2/keypair/{{ keyId.stdout }} --query Parameter.Value --with-decryption --output=text
  register: sshKey

- name: Create ssh key
  ansible.builtin.template:
    src: templates/ssh.j2
    dest: ~/.ssh/deployment-{{ deployment_number }}.key
    mode: "700"

- name: Get subnet 0
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      "tag:Name": sample-deployment-{{ deployment_number }}-subnet-0
  register: subnet_info_0

- name: Get subnet 1
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      "tag:Name": sample-deployment-{{ deployment_number }}-subnet-1
  register: subnet_info_1

- name: Get VPC prefix
  changed_when: vpc_prefix.rc != 0
  ansible.builtin.command: >
    aws ssm get-parameter --name /sample/vpc/cidr/prefix --query Parameter.Value --with-decryption --output=text
  register: vpc_prefix

- name: Get ec2 endpoint info
  amazon.aws.ec2_vpc_endpoint_info:
    filters:
      service-name: com.amazonaws.us-gov-west-1.ec2
  register: ec2_endpoint

- name: Get iam endpoint info
  amazon.aws.ec2_vpc_endpoint_info:
    filters:
      service-name: com.amazonaws.iam
  register: iam_endpoint

- name: Get elb endpoint info
  amazon.aws.ec2_vpc_endpoint_info:
    filters:
      service-name: com.amazonaws.us-gov-west-1.elasticloadbalancing
  register: elb_endpoint

- name: List all hosted zones
  amazon.aws.route53_info:
    query: hosted_zone
  register: hosted_zones

- name: Get zone id
  ansible.builtin.set_fact:
    matching_zone: "{{ zone.Id | regex_replace('/hostedzone/', '') }}"
  when: zone.Name == cluster_domain + '.'
  with_items: "{{ hosted_zones.HostedZones }}"
  loop_control:
    loop_var: zone

- name: Get RHCOS AMI IDs
  amazon.aws.ec2_ami_info:
    filters:
      name: "rhcos-{{ openshift_major_version }}{{ openshift_minor_version }}.*"
      architecture: "x86_64"
  register: ami_info

- name: Find Latest RHCOS AMI
  ansible.builtin.set_fact:
    rhcos_ami_id: "{{ ami_info.images | sort(attribute='creation_date', reverse=True) | map(attribute='image_id') }}"

- name: Generate install config
  ansible.builtin.template:
    src: "{{ source }}"
    dest: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/install-config.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Copy install config to cluster directory
  ansible.builtin.copy:
    src: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/install-config.yaml"
    dest: "{{ config_dir }}/deployment{{ deployment_number }}/ocp/cluster/install-config.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
