---

- name: Create temporary directory
  tempfile:
    state: directory
    suffix: _sample
  register: temp_dir
  notify:
    - Delete temporary directory

- name: Create AM password file
  copy:
    content: "{{ am_default_password }}"
    dest: "{{ temp_dir.path }}/pwd"
    owner: root
    group: root
    mode:  0400

- name: Batch process ssoadm commands
  command: >
    {{ ssoadm }} do-batch
      -c
      -u {{ am_admin_user }}
      -f {{ temp_dir.path }}/pwd
      -Z ssoadm-commands.batch
  args:
    chdir: "{{ sample_dir }}"
  register: cmd_result

- name: Show result in expanded format
  debug:
    var: cmd_result

- name: Search for built-in sample user
  command: >
    {{ ssoadm }} list-identities
      -u {{ am_admin_user }}
      -f {{ temp_dir.path }}/pwd
      -e {{ sample_realm }}
      -t User
      -x {{ sample_fqdn }}
  register: cmd_result
  changed_when: false

- name: Define user_found
  set_fact:
    user_found: "{{ 'no entries' not in cmd_result.stdout }}"

- name: Render user attributes
  template:
    src: user-attributes.txt.j2
    dest: "{{ temp_dir.path }}/user-attributes.txt"
    owner: root
    group: root
    mode:  0400
  when: not user_found

- name: Create built-in sample user
  command: >
    {{ ssoadm }} create-identity
      -u {{ am_admin_user }}
      -f {{ temp_dir.path }}/pwd
      -e {{ sample_realm }}
      -t User
      -i {{ sample_fqdn }}
      -D {{ temp_dir.path }}/user-attributes.txt
  when:
    - not user_found
    - ldap_server == 'msad-opendj' or ldap_server == 'opendj'

- name: Add built-in sample user to admin groups
  command: >
    {{ ssoadm }} add-member
      -u {{ am_admin_user }}
      -f {{ temp_dir.path }}/pwd
      -e {{ sample_realm }}
      -y User
      -m {{ sample_fqdn }}
      -t Group
      -i "{{ item }}"
  loop:
    - "{{ sample_owf_admin_group }}"
    - "{{ sample_owf_extern_admin_group }}"
  when:
    - not user_found
    - ldap_server == 'msad-opendj' or ldap_server == 'opendj'

- name: Restart JBoss
  systemd:
    name: jboss-eap-standalone
    state: restarted

