---

- name: Create sample directory
  file:
    path: "{{ sample_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Create entity-providers directory
  file:
    path: "{{ sample_dir }}/entity-providers"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Create symbolic link for entity-providers directory
  file:
    src:  "{{ sample_dir }}/entity-providers"
    dest: "{{ sample_dir }}/ep"
    state: link
    owner: root
    group: root

# Note: For the artifactory_sp.xml entity provider, the Location
# attribute in the AssertionConsumerService element must include the
# port number in the URL.

- name: Render entity-providers
  template:
    src: "entity-providers/{{ item }}.j2.xml"
    dest: "{{ sample_dir }}/entity-providers/{{ item }}.xml"
    owner: root
    group: root
    mode:  0644
  loop:
    - sample_idp
    - sample_idp-extended
    - artifactory_sp
    - artifactory_sp-extended
    - distributionfilter-api_sp
    - distributionfilter-api_sp-extended
    - install-manager_sp
    - install-manager_sp-extended
    - marketplace_sp
    - marketplace_sp-extended
    - owf_sp
    - owf_sp-extended

- name: Render ssoadm-commands.batch
  template:
    src: ssoadm-commands.batch.j2
    dest: "{{ sample_dir }}/ssoadm-commands.batch"
    owner: root
    group: root
    mode:  0644

- name: Copy over datastore-attributes files
  copy:
    src: "{{ item }}"
    dest: "{{ sample_dir }}"
    owner: root
    group: root
    mode:  0644
  loop:
    - datastore-attributes1.txt
    - datastore-attributes2.txt

