---

# This is a hack using the same certificate that the registry itself
# uses. Clients should ideally be using their own certificate and
# private key pair.

# Note: In docker, the client certificate had to have a .cert
# extension in order to be recognized as such. Not sure if this is
# the case with CRI-O. It needs to be confirmed through testing.

# Note: File mode 420 corresponds to octal 0644. File mode 384
# corresponds to octal 0600.

- name: Configure worker node CRI-O client certificate authentication to Application sample registry
  k8s:
    definition: 
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        labels:
          machineconfiguration.openshift.io/role: worker
        name: workers-crio-client-cert-auth-configuration
      spec:
        config:
          ignition:
            version: 3.2.0
          storage:
            files:
            - contents:
                source: "data:text/plain;charset=utf-8;base64,{{ rootchain_contents | b64encode }}"
              mode: 420
              overwrite: true
              path: "/etc/containers/certs.d/{{ sample_fqdn }}/ca.crt"
            - contents:
                source: "data:text/plain;charset=utf-8;base64,{{ certificate_contents | b64encode }}"
              mode: 420
              overwrite: true
              path: "/etc/containers/certs.d/{{ sample_fqdn }}/client.cert"
            - contents:
                source: "data:text/plain;charset=utf-8;base64,{{ private_key_contents | b64encode }}"
              mode: 384
              overwrite: true
              path: "/etc/containers/certs.d/{{ sample_fqdn }}/client.key"
    state: present

