---

- ansible.builtin.import_tasks: create-configmaps.yml

- ansible.builtin.import_tasks: create-services.yml

- ansible.builtin.import_tasks: create-deployments.yml

- ansible.builtin.import_tasks: create-routes.yml
