---

- name: Create temporary password file
  tempfile:
    state: file
    suffix: _sample
  register: result
  notify:
    - Delete temporary password file

- name: Extract path
  set_fact:
    pwd_file: "{{ result.path }}"

- name: Render AM password
  template:
    src: pwd.j2
    dest: "{{ pwd_file }}"
    owner: root
    group: root
    mode:  0400

- name: Remove sample user from admin groups
  command: >
    {{ ssoadm }} remove-member
      -u {{ am_admin_user }}
      -f {{ pwd_file }}
      -e {{ sample_realm }}
      -y User
      -m {{ sample_fqdn }}
      -t Group
      -i "{{ item }}"
  loop:
    - "{{ sample_owf_admin_group }}"
    - "{{ sample_owf_extern_admin_group }}"
  register: result
  changed_when:
    - result.rc == 0
  failed_when:
    - result.rc >= 1
    - ('not found' not in result.stderr)

- name: Delete sample user
  command: >
    {{ ssoadm }} delete-identities
      -u {{ am_admin_user }}
      -f {{ pwd_file }}
      -e {{ sample_realm }}
      -t User
      -i {{ sample_fqdn }}
  register: result
  changed_when:
    - result.rc == 0
  failed_when:
    - result.rc >= 1
    - ('does not exist' not in result.stderr)

- name: Delete sample entity providers
  command: >
    {{ ssoadm }} delete-entity
      -u {{ am_admin_user }}
      -f {{ pwd_file }}
      -e {{ sample_realm }}
      -y {{ item }}
  loop:
    - artifactory
    - distributionfilter-api
    - install-manager
    - marketplace
    - owf
    - "/{{ sample_realm }}/{{ sample_idp }}"
  register: result
  changed_when:
    - result.rc == 0
  failed_when:
    - result.rc >= 1
    - ('did not exist' not in result.stderr)

- name: Delete sample circle of trust (COT)
  command: >
    {{ ssoadm }} delete-cot
      -u {{ am_admin_user }}
      -f {{ pwd_file }}
      -e {{ sample_realm }}
      -t {{ sample_cot }}
  register: result
  changed_when:
    - result.rc == 0
  failed_when:
    - result.rc >= 1
    - ('is invalid' not in result.stderr)

