---
- name: Import Playbook.
  import_playbook: install-dependencies.yml
- name: Import Playbook.
  import_playbook: create-install-config.yml
- name: Import Playbook.
  import_playbook: create-roles.yml
- name: Import Playbook.
  import_playbook: create-manifests.yml
- name: Import Playbook.
  import_playbook: install-openshift.yml
- name: Import Playbook.
  import_playbook: set-kube.yml
