---

# Registry and repository prefix where App sample images are stored
pull_repository: "{{ ocp_registry_endpoint }}/application-sample"

# FQDN of App sample
sample_fqdn: "{{ sample_name }}.{{ apps_base_domain }}"

# Certificate alias of App sample
server_alias: "{{ sample_fqdn }}"

# Certificate alias of security server
idp_alias: "{{ groups.am[0] }}"


service_registry_password: "{{ vault_ocp_registry_password }}"


service_registry_password_secret_manifest:  "manifests/core/secret/service-registry-password.yml.j2"

installmanager_service_manifest:            "manifests/core/service/installmanager.yml.j2"

installmanagerdb_service_manifest:          "manifests/core/service/installmanagerdb.yml.j2"

installmanager_deploymentconfig_manifest:   "manifests/apps.openshift.io/deploymentconfig/installmanager.yml.j2"

installmanagerdb_deploymentconfig_manifest: "manifests/apps.openshift.io/deploymentconfig/installmanagerdb.yml.j2"
