---
- name: Remove immutable attribute on resolve.conf
  become: true
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command: chattr -i /etc/resolv.conf
- name: Reload NetworkManager service
  ansible.builtin.service:
    name: NetworkManager
    state: reloaded
