---
- name: Create Openshift Distributed Tracing namespace
  kubernetes.core.k8s:
    definition:
      apiVersion: project.openshift.io/v1
      kind: project
      metadata:
        name: openshift-distributed-tracing
    state: present
