---
- name: Import task.
  ansible.builtin.import_tasks: create-oor-namespace.yml
- name: Import task.
  ansible.builtin.import_tasks: create-odt-namespace.yml
- name: Import task.
  ansible.builtin.import_tasks: install-oeo.yml
- name: Import task.
  ansible.builtin.import_tasks: install-jaeger.yml
- name: Import task.
  ansible.builtin.import_tasks: install-kiali.yml
- name: Import task.
  ansible.builtin.import_tasks: install-osm.yml
