---

# Registry and repository prefix where App sample images are stored
pull_repository: "{{ ocp_registry_endpoint }}/application-sample"

# FQDN of App sample
sample_fqdn: "{{ sample_name }}.{{ apps_base_domain }}"

# Certificate alias of App sample
server_alias: "{{ sample_fqdn }}"

# Certificate alias of security server
idp_alias: "{{ groups.am[0] }}"


owf_service_manifest:            "manifests/core/service/owf.yml.j2"

owfdb_service_manifest:          "manifests/core/service/owfdb.yml.j2"

owf_deploymentconfig_manifest:   "manifests/apps.openshift.io/deploymentconfig/owf.yml.j2"

owfdb_deploymentconfig_manifest: "manifests/apps.openshift.io/deploymentconfig/owfdb.yml.j2"
