---

acs_am_keystore_path: "{{ keystore }}"

acs_am_keystore_pass: "{{ keystore_pass }}"


aa_am_keystore_path:  "{{ am_default_keystore_dir }}/aa_keystore.p12"

aa_am_keystore_pass:  "{{ acs_am_keystore_pass }}"

aa_am_keypass_path:   "{{ am_default_keystore_dir }}/.aa_keypass"

aa_am_storepass_path: "{{ am_default_keystore_dir }}/.aa_storepass"


ssoadm_dir: "/opt/ssoadm"

ssoadm_bin_dir: "{{ ssoadm_dir }}/{{ am_instance_name }}/bin"

ampassword: "{{ ssoadm_bin_dir }}/ampassword"

