---
- name: Play.
  hosts: localhost
  gather_facts: false
  roles:
    - maintenance-roles/docker_clean

- name: Play.
  hosts: master1
  gather_facts: false
  roles:
    - maintenance-roles/podman_clean
