#
# KeepAliveTimeout: Number of seconds to wait for the next request from the
# same client on the same connection.
#
KeepAliveTimeout 5

#
# Proxy Server directives. Uncomment the following lines to
# enable the proxy server:
#
<IfModule mod_proxy.c>
	SSLProxyEngine on
	ProxyRequests Off
	ProxyPreserveHost on

	ProxyPass /marketplace ajp://marketplace:8009/marketplace timeout=600  retry=0
	ProxyPass /owf ajp://owf:8009/owf  retry=0
	ProxyPass /install-manager ajp://installmanager:8009/install-manager  retry=0
	ProxyPass /install-manager-server ajp://installmanager:8009/install-manager-server  retry=0
	ProxyPass /distributionfilter-api ajp://distributionfilter-api:8009/distributionfilter-api  retry=0

	<ProxyMatch (.*)\.cache\.(.*)>
			Header Set Cache-Control "max-age=31536000, public"
	</ProxyMatch>

	<ProxyMatch green_(.*)\.png>
			Header Set Cache-Control "max-age=31536000, public"
	</ProxyMatch>

	<Proxy *>
		Order deny,allow
		Deny from all
		Allow from all
	</Proxy>
  RedirectMatch 302 ^/$ https://${PROXY_HOST}/owf
</IfModule>

