---
- name: Recursively change ownership of a directory
  become: true
  ansible.builtin.file:
    path: /opt
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"

- name: Create aws dir
  ansible.builtin.file:
    path: "~/.aws/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Create config file for AWS
  ansible.builtin.template:
    src: aws_config.yaml.j2
    dest: "~/.aws/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0640"

- name: Install boto3
  ansible.builtin.pip:
    name: boto3

- name: Install botocore
  ansible.builtin.pip:
    name: botocore

- name: Pip install kubernetes
  ansible.builtin.pip:
    name: kubernetes

- name: Unarchive openshift-client
  ansible.builtin.unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_major_version }}.{{ openshift_minor_version }}.{{ openshift_patch_version
      }}/openshift-client-linux.tar.gz
    dest: ~/.local/bin/
    remote_src: true

- name: Unarchive openshift-install
  ansible.builtin.unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_major_version }}.{{ openshift_minor_version }}.{{ openshift_patch_version
      }}/openshift-install-linux.tar.gz
    dest: ~/.local/bin/
    remote_src: true

- name: Unarchive helm
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v3.18.4-linux-amd64.tar.gz
    dest: ~/.local/bin/
    remote_src: true

- name: Move helm to correct directory.
  ansible.builtin.copy:
    src: "~/.local/bin/linux-amd64/helm"
    dest: "~/.local/bin/helm"
    mode: "0777"

- name: Remove existing helm symlink
  ansible.builtin.file:
    path: "/usr/bin/helm"
    state: absent
  become: true

- name: Create link for oc
  ansible.builtin.file:
    src: /home/{{ ansible_user }}/.local/bin/helm
    dest: /usr/bin/helm
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  become: true

- name: Remove existing oc symlink
  ansible.builtin.file:
    path: "/usr/bin/oc"
    state: absent
  become: true

- name: Create link for oc
  ansible.builtin.file:
    src: /home/{{ ansible_user }}/.local/bin/oc
    dest: /usr/bin/oc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  become: true

- name: Remove existing kubectl symlink
  ansible.builtin.file:
    path: "/usr/bin/kubectl"
    state: absent
  become: true

- name: Create link for oc
  ansible.builtin.file:
    src: /home/{{ ansible_user }}/.local/bin/kubectl
    dest: /usr/bin/kubectl
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  become: true

- name: Create pull secret file for ccoctl
  ansible.builtin.template:
    src: pull-secret.yaml.j2
    dest: "~/.pull-secret"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0640"

- name: Remove existing ccoctl
  ansible.builtin.file:
    path: "~/.local/bin/ccoctl"
    state: absent

- name: Remove existing ccoctl
  ansible.builtin.file:
    path: "~/.local/bin/ccoctl.rhel9"
    state: absent

- name: Install ccoctl
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.shell: >
    set -o pipefail
    . ~/.bashrc &&
    export RELEASE_IMAGE=$(openshift-install version | awk '/release image/ {print $3}') &&
    export CCO_IMAGE=$(oc adm release info --image-for='cloud-credential-operator' $RELEASE_IMAGE -a ~/.pull-secret) &&
    oc image extract $CCO_IMAGE --file="/usr/bin/ccoctl" -a ~/.pull-secret &&
    . ~/.bashrc
  args:
    chdir: ~/.local/bin/

# - name: Create symbolic link for entity-providers directory
#   file:
#     src:  ~/.local/bin/ccoctl.rhel9
#     dest: ~/.local/bin/ccoctl
#     state: link

- name: Make ccoctl executable
  ansible.builtin.file:
    path: ~/.local/bin/ccoctl
    mode: "0775"
