---

- name: Play.
  hosts: localhost
  gather_facts: no
  roles:
    - ocp-post-roles/configure_custom_webconsole_route
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/deployment{{ deployment_number }}-ocp.conf"