---
- name: Install httpd-tools
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command: >
    dnf install -y httpd-tools
  become: true

- name: Pip install passlib
  ansible.builtin.pip:
    name: passlib
