---

pki_subdir: "{{ lookup('first_found', pki_search_paths) | dirname | dirname }}"


application_fqdn: "{{ application_name }}.{{ apps_base_domain }}"


rootchain_file:   "{{ pki_subdir }}/tls-chain/{{ application_fqdn }}-rootchain.pem"

certificate_file: "{{ pki_subdir }}/other/{{ application_fqdn }}.pem"

private_key_file: "{{ pki_subdir }}/other/{{ application_fqdn }}.key"


rootchain_contents:   "{{ lookup('file', rootchain_file, rstrip=false) }}"

certificate_contents: "{{ lookup('file', certificate_file, rstrip=false) }}"

private_key_contents: "{{ lookup('file', private_key_file, rstrip=false) }}"
