---

- name: Create service accounts
  k8s:
    definition: "{{ lookup('template', common_serviceaccount_manifest) }}"
  loop:
    - "{{ sample_standard_serviceaccount }}"
    - "{{ sample_management_serviceaccount }}"

# Per application-sample software installation plan. (Need to
# investigate what this does, why it is required, and whether there
# are any important security considerations.)

- name: Set nonroot SCC priority to one
  k8s:
    definition:
      api_version: v1
      kind: SecurityContextConstraints
      metadata:
        name: nonroot
      priority: 1
    state: present

# Note: We need to use oc commands to add the security context
# constraint (SCC) to the service account because the Ansible k8s
# module overwrites the list of subjects in the SCC cluster role
# binding object instead of appending to it.

# Note: The following uses a cluster role binding to add the security
# context constraint (SCC) to the service account. This is a newer
# method introduced in OCP 4.5. Previously, an entry was made
# directly to the SCC object. That is now considered the legacy
# technique.

- name: Get nonroot SCC cluster role-binding info
  k8s_info:
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: "system:openshift:scc:nonroot"
  register: crb_result

# Note: The following uses the long-form service account name because
# using -n (--namespace) and -z (--serviceaccount) creates a plain
# role-binding, which is project-scoped. We need a cluster role-
# binding instead.

- name: Add nonroot SCC to sample standard service account
  command:
    cmd: "oc adm policy add-scc-to-user nonroot {{ sa_prefix }}:{{ sample_standard_serviceaccount }}"
  when: sample_standard_serviceaccount not in subject_names

- name: Add nonroot SCC to sample management service account
  command:
    cmd: "oc adm policy add-scc-to-user nonroot {{ sa_prefix }}:{{ sample_management_serviceaccount }}"
  when: sample_management_serviceaccount not in subject_names

# The check for an existing cluster role-binding between the sample
# management service account and the cluster-admin role is much
# easier than that for the nonroot SCC because in this case, we
# create a dedicated cluster role-binding with a unique, pre-
# determined name. It is enough to simply check if the binding exists
# without having to inspect its fields.

- name: Get sample-cluster-admin cluster role-binding info
  k8s_info:
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: sample-cluster-admin
  register: crb_result

- name: Add cluster-admin role to sample management service account
  command: >
    oc adm policy add-cluster-role-to-user cluster-admin
      --rolebinding-name=sample-cluster-admin
      --namespace=application-sample
      --serviceaccount={{ sample_management_serviceaccount }}
  when: not crb_result.resources

