---

- name: Create certificates configmap
  k8s:
    definition: "{{ lookup('template', certificates_configmap_manifest) }}"
  no_log: true

- name: Create aaproperties configmap
  k8s:
    definition: "{{ lookup('template', aaproperties_configmap_manifest) }}"

