---

- name: Create common secrets
  k8s:
    definition: "{{ lookup('template', common_secret_manifest) }}"
  loop:
    - name: artpass
      source: "{{ sample_artpass }}"
    - name: parent-artpass
      source: "{{ sample_parent_artpass }}"
    - name: dbpass
      source: "{{ sample_dbpass }}"
    - name: keypassword
      source: "{{ sample_key_password }}"
    - name: keystorepassword
      source: "{{ sample_keystore_password }}"
    - name: newkeystorepassword
      source: "{{ sample_new_keystore_password }}"
    - name: newtruststorepassword
      source: "{{ sample_new_truststore_password }}"
    - name: spkeypassword
      source: "{{ sample_sp_key_password }}"
  no_log: true

- name: Create registry-credentials secret
  k8s:
    definition: "{{ lookup('template', registry_credentials_manifest) }}"
  no_log: true

- name: Get sample standard service account info
  k8s_info:
    api_version: v1
    kind: serviceaccount
    name: "{{ sample_standard_serviceaccount }}"
    namespace: application-sample
  register: sa_result

- name: Link registry-credentials secret to sample standard service account
  command: >
    oc secret link {{ sample_standard_serviceaccount }} registry-credentials
      --namespace=application-sample
      --for=pull
  when: ('registry-credentials' not in image_pull_secrets)

- name: Get sample management service account info
  k8s_info:
    api_version: v1
    kind: serviceaccount
    name: "{{ sample_management_serviceaccount }}"
    namespace: application-sample
  register: sa_result

- name: Link registry-credentials secret to sample management service account
  command: >
    oc secret link {{ sample_management_serviceaccount }} registry-credentials
      --namespace=application-sample
      --for=pull
  when: ('registry-credentials' not in image_pull_secrets)

