---
- name: Get subnet 0
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      "tag:Name": sample-deployment-{{ deployment_number }}-subnet-0
    region: "{{ aws_region }}"
  register: subnet_info_0

- name: Get subnet 1
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      "tag:Name": sample-deployment-{{ deployment_number }}-subnet-1
    region: "{{ aws_region }}"
  register: subnet_info_1

- name: Render exports file
  template:
    src: exports.j2
    dest: /etc/exports.d/deployment{{ deployment_number }}.exports
    owner: root
    group: root
    mode:  0644
  notify: Refresh exports
  become: true
  become_user: root
