---

# - ansible.builtin.import_tasks: firewall.yml

- ansible.builtin.import_tasks: package.yml

- ansible.builtin.import_tasks: nfs-dir.yml

- ansible.builtin.import_tasks: sub-dirs.yml

- ansible.builtin.import_tasks: configs.yml
