---

# - name: Import task.
  import_tasks: firewall.yml

- name: Import task.
  import_tasks: package.yml

- name: Import task.
  import_tasks: nfs-dir.yml

- name: Import task.
  import_tasks: sub-dirs.yml

- name: Import task.
  import_tasks: configs.yml
