---
- name: Configure NFS sub-directories shares
  ansible.builtin.file:
    path: "{{ nfs_dir }}/{{ item.name }}"
    state: directory
    owner: nobody
    group: nobody
    mode: "0777"
  loop: "{{ ocp4_nfs_volumes }}"
  become: true

- name: Create mount points for persistent storage and Docker registry
  ansible.builtin.file:
    path: "{{ nfs_dir }}/registry"
    state: directory
    owner: nobody
    group: nobody
    mode: "0777"
  become: true
