# Common Properties File

# Locations of certificates for install
INSTALL_PATH: "/opt/applicationsample"

# This directory should contain all CA certs needed for install
CA_CERT_DIR: "{{ INSTALL_PATH }}/certs/ca"

# This directory should contain at minimum the server p12 file. It
# could also contain either the the SP p12 file or the IdP p12 file
# depending on the type ie sec or app
SERVER_CERT_DIR: "{{ INSTALL_PATH }}/certs/server"

# TLS Key config properties
path_to_private_crt: "/etc/pki/tls/private"
path_to_public_cert: "/etc/pki/tls/certs"
path_to_root_crt: "/etc/pki/tls/certs"
server_cert: "/etc/pki/tls/certs/public.crt"
server_ca: "/etc/pki/tls/certs/cabundle.crt"
private_key: "/etc/pki/tls/private/private.key"
keystoreFile: "/etc/pki/tls/certs/keystore.p12"
trustStoreFile: "/etc/pki/tls/certs/keystore.p12"

# FQDN of database server
OWFDB_FQDN: owfdb
MARKETPLACEDB_FQDN: marketplacedb
INSTALLMANAGERDB_FQDN: installmanagerdb
DISTRIBUTIONFILTERDB_FQDN: distributionfilterdb

# Database Install Variables
DBUSER: storefront
DBNAME: storefront

# Artifactory Install Variables
ARTUSER: admin
PARENT_ARTUSER: admin

# SSO Install Variables

# Set to true if using root realm and set to false if using a child realm
root_realm: false

# Use <realm>/<idp> for a child realm
idp_name: "sample/sample"

# HTTPD Variables
SSL_VERIFY: require

# DIL Variables
DIL_LOG_LEVEL: INFO
DIL_CA_KEY: "/opt/applicationsample/dil/ca/dil-ca.key"
DIL_CA_CERT: "/opt/applicationsample/dil/ca/dil-ca.crt"
DIL_CERT_YEARS: 50
DIL_ISSUER: appsample-dil-services-ca
DIL_PROXY_CONNECTION_TIMEOUT: 120000
DIL_PROXY_RETRY_COUNT: 50
DIL_PROXY_RETRY_TIMER: 5000

# Install Manager configuration - some or all is needed for
# OWF/Marketplace
APPLICATION_REPO: applications
PARENT_APPLICATION_REPO: applications
IMAGE_REPO: docker
PARENT_IMAGE_REPO: docker
HISTORY_REPO: history
STAGING_SUFFIX: staging
IM_DOWNLOAD_TIMEOUT: 10000
IM_DOWNLOAD_THREADS: 1
OWF_PATH: owf
WIDGET_DEF_DIR: widget-definitions
MARKETPLACE_PATH: marketplace
MARKETPLACE_DEF_DIR: marketplace-definitions
IM_LOG_DIR: "/usr/share/tomcat/logs"
IM_LOG_LEVEL: INFO
VOLUME_RETENTION_POLICY: Retain
sample_OPENSHIFT_PROJECT: application-sample

# Groovy config parameters
dbType: postgresql
dbPort: 5432
driverClassName: "org.postgresql.Driver"
dialect: "org.hibernate.dialect.PostgreSQLDialect"
DB_ENCRYPT: "?ssl=true"

# Syslog parameters
syslog_remote_server_hostname: "ansible.dvi.lab.net"
syslog_remote_server_port: 514
syslog_enabled: false

# Classification Banner Configuration
CLASSIFICATION_STRING: "{{ sample_classification_banner_string }}"
CLASSIFICATION_BACKGROUND_COLOR: "{{ sample_classification_banner_background_color }}"
CLASSIFICATION_FONT_COLOR: "{{ sample_classification_banner_font_color }}"

# VST VARS
ELASTICSEARCH_USERNAME: elastic
ELASTICSEARCH_PASSWORD: password2
ELASTIC_PASSWORD: password2
LOGSTASH_BEATS_PORT: 5044
LOGSTASH_HTTP_PORT: 8080
LOGSTASH_HEARTBEAT_INTERVAL: 60
LOGSTASH_HOST: logstash
ELASTIC_FQDN: elasticsearch
polling_enabled: false
openshift_paths: "/oapi/v1/watch/deploymentconfigs,/api/v1/watch/services,/api/v1/watch/secrets,/apis/route.openshift.io/v1/watch/routes,/api/v1/watch/configmaps,/api/v1/watch/persistentvolumeclaims,/oapi/v1/watch/deploymentconfigs?export=false"

# Twinning DB Variables
TWINDB_USER: storefront
TWINDB_FQDN: twinningdb
TWINDB_NAME: storefront
