# App Configuration

# Zone for server (i.e. 'ti', 'prod' for ashore, or 'edge' for
# afloat).
zone: edge

# Type of server (i.e. 'app' for application server, 'sec' for
# security server, 'vst' for virtual software twin server, or 'ss'
# for single server (app + sec)).
type: app

# This is only required for afloat deployments, should be set to the
# name of the ship, this is used by the distribution filter to
# determine what files to receive.
SITE_NAME: "{{ sample_site_name }}"

# Used by HTTPD for Artifactory
PROXY_HOST: "{{ sample_fqdn }}"

# FQDN of security server
sso_fqdn: "{{ groups.am[0] }}:8443"
sso_ip: "{{ hostvars[groups.am[0]].ansible_facts.default_ipv4.address }}"

# SSO install variables
cookie: ".{{ apps_base_domain }}"

# FQDN of parent server
parent_sample_fqdn: "{{ sample_parent_fqdn }}"
parent_sample_ip: "{{ sample_parent_ip }}"

# Registry and repository prefix where Application sample images are stored.
# This should probably use ocp_registry_endpoint
pull_repository: "{{ ocp_registry_endpoint }}/application-sample"

# Name of the repository where Application sample Update Images will
# be stored (ONLY TO BE USED FOR OPENSHIFT DEPLOYMENTS).
# example: docker.registry.net:5000
SERVICE_REGISTRY: "{{ ocp_registry_endpoint }}"

# URL of the repository where Application sample Update Images will
# be stored (ONLY TO BE USED FOR OPENSHIFT DEPLOYMENTS).
# example: https://docker.registry.net:5000
SERVICE_REGISTRY_URL: "https://{{ SERVICE_REGISTRY }}"

# Username of the account on the service docker registry where
# Application sample Update Images will be stored (ONLY TO BE USED
# FOR OPENSHIFT DEPLOYMENTS)
SERVICE_REGISTRY_USERNAME: "{{ vault_ocp_registry_username }}"

openam_org_dn: "dc=openam,dc=forgerock,dc=org"

# Already specified in defaults/main.yml
#sample_fqdn: {{ sample_fqdn }}

server_alias: "{{ sample_fqdn }}"
sp_alias: "{{ sample_fqdn }}"

# Certificate alias of security server
idp_alias: "{{ groups.am[0] }}"

# Not required anymore in sample 1.1.2.0+
# OpenShift web console
#openshiftUrl: "https://{{ sample_openshift_fqdn }}:443"

## Groovy config parameters

# Use '3' for edge
environmentLevel: 3

# Use 'NTCMP' for edge
environmentName: NTCMP

# Use 'ntc' for edge
defaultTheme: ntc

# Use "Application sample - Afloat" for edge
# Note: The double quotes are required
storename: "Application sample - Afloat"

# Use 'ntc' for edge
themename: ntc

# FQDN of the ashore server hosting vst
vst_fqdn: "vst.example.sample.mil"

# Set to true when you are using a GlusterFS persistent storage
GLUSTERFS: true
