---

# Registry and repository prefix where App sample images are stored
pull_repository: "{{ ocp_registry_endpoint }}/application-sample"

# FQDN of App sample
sample_fqdn: "{{ sample_name }}.{{ apps_base_domain }}"

# Certificate alias of App sample
server_alias: "{{ sample_fqdn }}"

# Certificate alias of security server
idp_alias: "{{ groups.am[0] }}"


dil_ca_certificate_file: "{{ pki_dir }}/sample/workspace/dil-ca.crt"

dil_ca_privatekey_file:  "{{ pki_dir }}/sample/workspace/dil-ca.key"


dil_services_configmap_manifest:        "manifests/core/configmap/dil-services.yml.j2"

dil_services_service_manifest:          "manifests/core/service/dil-services.yml.j2"

dil_services_deploymentconfig_manifest: "manifests/apps.openshift.io/deploymentconfig/dil-services.yml.j2"
