---

- name: Create owf database service
  k8s:
    definition: "{{ lookup('template', owfdb_service_manifest) }}"

- name: Create owf service
  k8s:
    definition: "{{ lookup('template', owf_service_manifest) }}"

