---

- name: Render dhclient.conf
  template:
    src: dhclient.conf.j2
    dest: /etc/dhcp/dhclient.conf
    owner: root
    group: root
    mode:  0644

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted

