---
- name: Create binary file
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.shell: |
    set -o pipefail
    cat {{ config_dir }}/deployment{{ deployment_number }}/ocp/htpasswdfile \
    | base64 -w0 > {{ config_dir }}/deployment{{ deployment_number }}/ocp/htpasswdfile.dat

- name: Create secret for htpasswd
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: htpass-secret
        namespace: openshift-config
      type: Opaque
      data:
        htpasswd: "{{ lookup('file', '{{ config_dir }}/deployment{{ deployment_number }}/ocp/htpasswdfile.dat') }}"
    state: present
