---

- name: Create binary file
  shell: "cat {{ config_dir }}/deployment{{ deployment_number }}/ocp/htpasswdfile | base64 -w0 > {{ config_dir }}/deployment{{ deployment_number }}/ocp/htpasswdfile.dat"

- name: Create secret for htpasswd
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: htpass-secret
        namespace: openshift-config
      type: Opaque
      data:
        htpasswd: "{{ lookup('file', '{{ config_dir }}/deployment{{ deployment_number }}/ocp/htpasswdfile.dat') }}"
    state: present