---
- name: Import task.
  ansible.builtin.import_tasks: create_secret.yml
- name: Import task.
  ansible.builtin.import_tasks: configure_oauth.yml
- name: Import task.
  ansible.builtin.import_tasks: configure_user.yml
