---
- name: Import Playbook.
  import_playbook: ocp-aux/api-int-lb/api-int-lb.yml

- name: Import Playbook.
  import_playbook: ocp-aux/api-lb/api-ext-lb.yml

- name: Import Playbook.
  import_playbook: ocp-aux/ingress-lb/ingress-lb.yml
