---

sample_dir: "/opt/applicationsample"


aa_am_keystore_path:  "{{ am_default_keystore_dir }}/aa_keystore.p12"

aa_am_keypass_path:   "{{ am_default_keystore_dir }}/.aa_keypass"

aa_am_storepass_path: "{{ am_default_keystore_dir }}/.aa_storepass"

cert_alias: "{{ groups.am[0] }}"


am_url: "{{ am_protocol }}://{{ groups.am[0] }}:{{ am_port }}/{{ am_instance_name }}"


sample_fqdn: "{{ sample_name }}.{{ apps_base_domain }}"

sample_protocol: https

sample_port: "443"

sample_url: "{{ sample_protocol }}://{{ sample_fqdn }}"


pki_subdir: "{{ lookup('first_found', pki_search_paths) | dirname | dirname }}"

begin_marker: '-----BEGIN CERTIFICATE-----\n'

end_marker: '\n-----END CERTIFICATE-----'

am_certificate_file: "{{ pki_subdir }}/server/{{ groups.am[0] }}.pem"

am_certificate: "{{ lookup('file', am_certificate_file) }}"

am_certificate_body: "{{ am_certificate | regex_replace(begin_marker) | regex_replace(end_marker) }}"

sample_certificate_file: "{{ pki_subdir }}/other/{{ sample_fqdn }}.pem"

sample_certificate: "{{ lookup('file', sample_certificate_file) }}"

sample_certificate_body: "{{ sample_certificate | regex_replace(begin_marker) | regex_replace(end_marker) }}"


ssoadm_dir: "/opt/ssoadm"

ssoadm_bin_dir: "{{ ssoadm_dir }}/{{ am_instance_name }}/bin"

ssoadm: "{{ ssoadm_bin_dir }}/ssoadm"


# Determines whether or not to enable the new XUI interface in AM.
# This was previously known to cause problems with sample SAML
# authentication.
sample_enable_xui: true

sample_realm: "sample"

sample_cot: "sample"

sample_idp: "sample"

# Name of the IDP. Should be formatted like <realm>/<idp>.
# This might not get used at all in this role.
#sample_idp_name: "sample/sample"
